parameters:
  - name: Run_Stage
    displayName: Stage to Run
    type: string
    default: 'Deploy_Full'
    values:
    - Deploy_Full

  - name: location
    displayName: Location
    type: string
    default: 'UK South'
    values:
    - 'UK South'
    - 'UK West'

  - name: env
    displayName: Environment
    type: string
    default: 'PROD'
    values:
    - PROD
          
name: HMCTS Shared Services AKS Azure Infrastructure Deployment Pipeline
trigger:
- none

variables:
  - name: gaServiceConnection
    value: OPS-APPROVAL-GATE-${{ parameters.env }}-ENVS
  - name: tfversion
    value: 0.13.4
  # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
  # but it might be better to template the pipeline more and have a different pipeline file
  # so that someone doesn't pick the wrong var in the dropdown
  - name: project
    value: pet
  # same comment as above ^^
  - name: serviceConnection
    value: OPS-APPROVAL-GATE-${{ parameters.env }}-ENVS}

stages:

  - stage: frontdoor
    displayName: 'frontdoor'
    condition: contains('${{ parameters.Run_Stage }}', 'Deploy_Full')
    jobs:
      - job: DeployInfrastructure
        steps:
          - template: pipeline-steps/frontdoor.yaml
            parameters:
              environment: ${{ parameters.env }}
              location: ${{ parameters.location }}
              stack: 'frontdoor'
              project: $(project)
              tfversion: $(tfversion)
